### ISSUE TITLE
On \ Off for x10 should be Off \ On

### ISSUE THREAD

**Issue by hanssipi** [pilight/pilight#151]
`pilight-daemon version 6.0, commit v6.0`
`Linux 3.12.31 #2 PREEMPT Wed Oct 29 09:24:56 UTC 2014 armv6l GNU/Linux`

Pi B

Small issue X10.

Tried my old X10 devices today with pilight 6.0 and works well!!
The only thing i've found sofar, is the device "state": ON=off and OFF=on
```
"Dev1": {
	"protocol": [ "x10" ],
	"id": [{
		"id": "A9"
	}],
	"state": "off"
}
```
is actually "ON". The webgui buttons are off but i have to press them twice to switch A9 on. Ofcource then the button says "off" again.

The commandline `/usr/local/bin/pilight-send -p x10 -i A9 -t` should turn A9 ON, but it goes OFF.

Cheers!

**Comment by wo-rasp** [comment]
Unsure if I should have done it in the development branch directly or via Pull Request.
Fixed with Pull Request #152

**Comment by CurlyMoo** [comment]
You can fix these small changes directly.

**Comment by CurlyMoo** [comment]
@hanssipi, can you test the fix @wo-rasp did?

**Comment by hanssipi** [comment]
@CurlyMoo  Shure, euhh how do i get the fix? Never done that before.

**Comment by CurlyMoo** [comment]
By following the manual install guide on pilight.org

**Comment by hanssipi** [comment]
@CurlyMoo nothing changed! Still the same.

Is this correct?

apt-get install pilight
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  javascript-common libjs-excanvas libjs-mochikit wwwconfig-common
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  pilight-webgui
Suggested packages:
  php5-cgi pilight-firmware
The following NEW packages will be installed:
  pilight pilight-webgui
0 upgraded, 2 newly installed, 0 to remove and 127 not upgraded.
Need to get 2148 kB of archives.
After this operation, 10.8 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://apt.pilight.org/ stable/main pilight-webgui armhf 6.0 [553 kB]
Get:2 http://apt.pilight.org/ stable/main pilight armhf 6.0 [1595 kB]
Fetched 2148 kB in 1s (1146 kB/s)
Selecting previously unselected package pilight-webgui.
(Reading database ... 51078 files and directories currently installed.)
Unpacking pilight-webgui (from .../pilight-webgui_6.0_armhf.deb) ...
Selecting previously unselected package pilight.
Unpacking pilight (from .../archives/pilight_6.0_armhf.deb) ...
Setting up pilight-webgui (6.0) ...
Setting up pilight (6.0) ...

**Comment by CurlyMoo** [comment]
No, the manually compile guide.

**Comment by hanssipi** [comment]
Did that to:

But,
...........
Scanning dependencies of target pilight_shared
Linking C shared library libpilight.so
[ 93%] Built target pilight_shared
Scanning dependencies of target pilight-control
[ 94%] Building C object CMakeFiles/pilight-control.dir/control.c.o
Linking C executable pilight-control
libpilight.so: undefined reference to `pcap_sendpacket'
libpilight.so: undefined reference to `pcap_dispatch'
libpilight.so: undefined reference to `pcap_close'
libpilight.so: undefined reference to `pcap_open_live'
libpilight.so: undefined reference to `pcap_geterr'
libpilight.so: undefined reference to `pcap_get_selectable_fd'
libpilight.so: undefined reference to `pcap_setnonblock'
collect2: ld returned 1 exit status
make[2]: *** [pilight-control] Error 1
make[1]: *** [CMakeFiles/pilight-control.dir/all] Error 2
make: *** [all] Error 2

**Comment by CurlyMoo** [comment]
Can you please post according to these rules:
https://github.com/pilight/pilight/blob/master/CONTRIBUTING.md
