### ISSUE TITLE
api.wunderground.com response was not in a valid json format

### ISSUE THREAD

**Issue by fscoelho** [pilight/pilight#161]
After upgrading from version 6.0 commit 6.0 ( base) the wunderground
does not work any more. api.wunderground.com response was not in a valid json format

[Mar 23 22:26:07:966425] pilight-daemon: INFO: version 6.0, commit v6.0-63-g5afaeab
[ Mar 23 22:26:08:66140] pilight-daemon: NOTICE: no pilight daemon found, daemonizing
[ Mar 23 22:26:08:68215] pilight-daemon: INFO: daemon listening to port: 39089
[ Mar 23 22:26:08:99892] pilight-daemon: INFO: new client, ip: 127.0.0.1, port: 55795
[Mar 23 22:26:08:226964] pilight-daemon: INFO: new client, ip: 192.168.1.112, port: 39468
[Mar 23 22:26:08:233511] pilight-daemon: INFO: datetime #1 -8.637476:41.255146 adjusted by 0 seconds

[Mar 23 22:26:08:237993] pilight-daemon: INFO: new client, ip: 192.168.1.112, port: 39469
[Mar 23 22:26:08:949104] pilight-daemon: INFO: datetime #1 -8.637476:41.255146 seems to be in timezone: Europe/Lisbon
[Mar 23 22:26:09:116599] pilight-daemon: ERROR: cpu usage too high 88.896443%
[Mar 23 22:26:09:117891] pilight-daemon: ERROR: checking again in 10 seconds
[ Mar 23 22:26:10:38311] pilight-daemon: NOTICE: api.wunderground.com response was not in a valid json format

**Comment by CurlyMoo** [comment]
Issue not opened in line with the rules so closed.
