### ISSUE TITLE
pilight-send dont control dimlevel limits

### ISSUE THREAD

**Issue by fscoelho** [pilight/pilight#164]
pilight-send dont control generic_dimmer with limits between 1 and 8.
Gives error only in 11 , but if we define a value over 10 will be not accepted. It seems 10 it a built in limit and dont care about device definitions
"dimlevel-minimum": 1,
"dimlevel-maximum": 8

pi@raspberrypi:~$ pilight-send -p generic_dimmer -i 203 -d 7 -t
pi@raspberrypi:~$ pilight-send -p generic_dimmer -i 203 -d 8 -t
pi@raspberrypi:~$ pilight-send -p generic_dimmer -i 203 -d 9 -t
pi@raspberrypi:~$ pilight-send -p generic_dimmer -i 203 -d 10 -t
pi@raspberrypi:~$ pilight-send -p generic_dimmer -i 203 -d 11 -t
[Mar 23 00:25:00:472669] pilight-send: ERROR: generic_dimmer: invalid dimlevel range

configuration device:

        "dimmer": {
            "protocol": [ "generic_dimmer" ],
            "id": [{
                "id": 203
            }],
            "state": "on",
            "dimlevel": 5,
            "dimlevel-minimum": 1,
            "dimlevel-maximum": 8
        }

**Comment by CurlyMoo** [comment]
Issue not opened according to the rules so closing.
