### ISSUE TITLE
generic_label action  truncates numbers with decimals

### ISSUE THREAD

**Issue by fscoelho** [pilight/pilight#172]
The problem with display of numbers with the generic_label is not fully solved.
when using "2.12" there is a truncation and will display only "2"
I my opinion the label should display exacly what is wrote , that means should consider as a string always. Was not the cases

pilight version
```
pilight-daemon version 6.0, commit 538cd30
```

```
pi@raspberrypi:~$ pilight-send -p generic_label -i 1 -l "2.12" -c 1

```
Show i the web-gui 

```
2

```

**Comment by CurlyMoo** [comment]
Fixed
