### ISSUE TITLE
Nightly compile error on RPi2 (Jessie)

### ISSUE THREAD

**Issue by Warter21** [pilight/pilight#179]
I tried to compile latest nightly build but I got this error:
```
[ 28%] Building C object CMakeFiles/pilight.dir/libs/polarssl/bignum.c.o
/root/pilight/libs/polarssl/bignum.c: In function 'mpi_mul_hlp':
/root/pilight/libs/polarssl/bignum.c:1129:1: error: r7 cannot be used in asm here
}
^
CMakeFiles/pilight.dir/build.make:1483: recipe for target 'CMakeFiles/pilight.dir/libs/polarssl/bignum.c.o' failed
make[2]: *** [CMakeFiles/pilight.dir/libs/polarssl/bignum.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pilight.dir/all' failed
make[1]: *** [CMakeFiles/pilight.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```
The stable release was compiled without any problem and working like a charm.

**Comment by CurlyMoo** [comment]
What version of gcc are you using?

**Comment by Warter21** [comment]
root@jessie-rpi:~# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by CurlyMoo** [comment]
Please use github markdown for readability.

**Comment by Warter21** [comment]
I think there is a [solution](https://tls.mbed.org/kb/development/arm-thumb-error-r7-cannot-be-used-in-asm-here), please check it. Thanks

**Comment by CurlyMoo** [comment]
Thanks. Can you still format your previous post according to my comment?

**Comment by Warter21** [comment]
It seems It is fixed the problem to change "-Wall" to "-Wall -O2".
Unfortunately there is another problem with SSL. It looks like there are missing some compile options like "-lssl -lcryto".

**Comment by CurlyMoo** [comment]
If you want to compile the webserver SSL, it's not supported althought possible. Please refer to the forum post about it.

**Comment by CurlyMoo** [comment]
Also, if you want to compile with this specific gcc version do inside the pilight source root:
```
mkdir build
cd build
cmake .. -DCMAKE_C_FLAGS=-fomit-frame-pointer
make
```
