### ISSUE TITLE
X10 protocol pilight

### ISSUE THREAD

**Issue by hanssipi** [pilight/pilight#180]
Hi,

Small issue with X10 here. The X10 code A8 seems to be operating A9 when using webgui.
I have 2 lights on A8 and A9. The lamp on A9 switches on and off when i use A8.

 "TVlamp": {
         "protocol": [ "x10" ],
         "id": [{
                 "id": "A8"
          }],
          "state": "off"
 },
 
Greetz!

**Comment by NiekD** [comment]
Did you really intend to assign this issue to me?
I don't own any X10 devices to test with and never used this protocol 
myself :-\ .

CurlyMoo schreef op 17-6-2015 om 10:29:

**Comment by CurlyMoo** [comment]
I also don't own X10 devices, as with most devices pilight supports :smile:

However, the protocol is pretty well documented so it shouldn't be that difficult.

**Comment by NiekD** [comment]
Ok, I will give it a try.

@hanssipi

Could you please post your config.json (please be sure to mask any 
passwords and such before you post)?

CurlyMoo schreef op 18-6-2015 om 12:44:

**Comment by hanssipi** [comment]
{
	"devices": {
		"Gang": {
			"protocol": [ "generic_webcam" ],
			"id": [{
				"id": 100
			}],
			"url": "http://xxxxx/snapshot.cgi?user=admin&pwd=xxxxx",
			"poll-interval": 1000
		},
		"Huiskamer": {
			"protocol": [ "generic_webcam" ],
			"id": [{
				"id": 102
			}],
			"url": "http://xxxxx/snapshot.cgi?user=admin&pwd=xxxxx",
			"poll-interval": 1000
		},
		"Keuken": {
			"protocol": [ "generic_webcam" ],
			"id": [{
				"id": 103
			}],
			"url": "http://xxxxx/snapshot.cgi?user=admin&pwd=xxxxx",
			"poll-interval": 1000
		},
		"Schuur": {
			"protocol": [ "generic_webcam" ],
			"id": [{
				"id": 104
			}],
			"url": "http://xxxxx/snapshot.cgi?user=admin&pwd=xxxxx",
			"poll-interval": 1000
		},
		"groepgordijnen": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A12"
			}],
			"state": "on"
		},
		"groepkika": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 4
			}],
			"state": "off"
		},
		"Beganegrondkeuken": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 0
			}],
			"state": "off"
		},
		"Beganegrondgang": {
			"protocol": [ "kaku_switch", "kaku_motion" ],
			"id": [{
				"id": 10295390,
				"unit": 1
			},
			{
				"id": 14277794,
				"unit": 9
			}],
			"state": "off"
		},
		"Beganegrondvoordeur": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 2
			}],
			"state": "off"
		},
		"Slaapkamerkast": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 12
			}],
			"state": "off"
		},
		"Zolder": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 8
			}],
			"state": "off"
		},
		"Zoldertrap": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 13
			}],
			"state": "off"
		},
		"Douche": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 14
			}],
			"state": "off"
		},
		"Overloop": {
			"protocol": [ "kaku_switch" ],
			"id": [{
				"id": 10295390,
				"unit": 15
			}],
			"state": "off"
		},
		"TVlamp": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A8"
			}],
			"state": "off"
		},
		"GordijnL": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A7"
			}],
			"state": "on"
		},
		"GordijnR": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A11"
			}],
			"state": "on"
		},
		"TVlampL": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A5"
			}],
			"state": "off"
		},
		"Klok": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A6"
			}],
			"state": "on"
		},
		"Boom": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A1"
			}],
			"state": "off"
		},
		"Bak": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A2"
			}],
			"state": "off"
		},
		"Eet": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A4"
			}],
			"state": "off"
		},
		"Salon": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A3"
			}],
			"state": "off"
		},
		"Lgor": {
			"protocol": [ "x10" ],
			"id": [{
				"id": "A9"
			}],
			"state": "off"
		}
	},
	"rules": {
		"gordijnenD": {
			"rule": "IF groepgordijnen.state IS on THEN switch DEVICE GordijnR TO on AND switch DEVICE GordijnL TO on",
			"active": 1
		},
		"gordijnenO": {
			"rule": "IF groepgordijnen.state IS off THEN switch DEVICE GordijnR TO off AND switch DEVICE GordijnL TO off",
			"active": 1
		},
		"BG-Groep-KIKA-aan": {
			"rule": "IF groepkika.state IS on THEN switch DEVICE Beganegrondkeuken TO on AND switch DEVICE Beganegrondvoordeur TO on AND switch DEVICE Beganegrondgang TO on",
			"active": 1
		},
		"BG-Groep-KIKA-uit": {
			"rule": "IF groepkika.state IS off THEN switch DEVICE Beganegrondkeuken TO off AND switch DEVICE Beganegrondvoordeur TO off AND switch DEVICE Beganegrondgang TO off",
			"active": 1
		}
	},
	"gui": {
		"Gang": {
			"name": "Webcam",
			"group": [ "Camera" ]
		},
		"Huiskamer": {
			"name": "Huiskamer",
			"group": [ "Camera" ]
		},
		"Keuken": {
			"name": "Keuken",
			"group": [ "Camera" ]
		},
		"Schuur": {
			"name": "Schuur",
			"group": [ "Camera" ]
		},
		"groepkika": {
			"name": "Onderstaande lampen.",
			"group": [ "Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Beganegrondkeuken": {
			"name": "Keukenlamp",
			"group": [ "Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Beganegrondgang": {
			"name": "Ganglamp",
			"group": [ "Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Beganegrondvoordeur": {
			"name": "Voordeurlamp",
			"group": [ "Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Slaapkamerkast": {
			"name": "Slaapkamerkast verlichting",
			"group": [ "Eerste etage" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Zoldertrap": {
			"name": "Zoldertrap verlichting",
			"group": [ "Eerste etage" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Zolder": {
			"name": "Zolder verlichting",
			"group": [ "Eerste etage" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Douche": {
			"name": "Douche verlichting",
			"group": [ "Eerste etage" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Overloop": {
			"name": "Overloop verlichting",
			"group": [ "Eerste etage" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"TVlamp": {
			"name": "Lamp achter de TV",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"GordijnL": {
			"name": "Gordijn Links",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"GordijnR": {
			"name": "Gordijn Rechts",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"groepgordijnen": {
			"name": "Gordijnen.",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"TVlampL": {
			"name": "Lamp naast de TV",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Klok": {
			"name": "Klok",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Boom": {
			"name": "Voortuin boom verlichting",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Bak": {
			"name": "Voortuin bak voor verlichting",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Eet": {
			"name": "Eettafellamp",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Salon": {
			"name": "Salontafellamp",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		},
		"Lgor": {
			"name": "Lamp bij het gordijn.",
			"group": [ "X10 Beganegrond" ],
			"media": [ "all" ],
			"readonly": 0
		}
	},
	"settings": {
		"port": xxxxx,
		"log-level": 6,
		"pid-file": "/var/run/pilight.pid",
		"log-file": "/var/log/pilight.log",
		"webserver-enable": 1,
		"webserver-http-port": xxxx,
		"webserver-root": "/usr/local/share/pilight/",
		"webserver-cache": 1
	},
	"hardware": {
		"433gpio": {
			"sender": 0,
			"receiver": 4
		}
	},
	"registry": {
		"pilight": {
			"firmware": {
				"version": 3497,
				"lpf": 425100,
				"hpf": 409830
			},
			"version": {
				"current": "7.0"
			}
		}
	}
}

**Comment by CurlyMoo** [comment]
I think you agree with us that your comment is pretty unreadible. Please use `github markdown` to fix it (search it if unknown).

**Comment by CurlyMoo** [comment]
Should've been fixed.
