### ISSUE TITLE
Can't use only one transmitter at a time

### ISSUE THREAD

**Issue by gregnau** [pilight/pilight#187]
When transmitting commands pilight is (as the manual also states) sending it on all transmitters.
I've tried to avoid it with using the "uuid" line in the device config, but it's still transmitting on every TX.

This would be very good to have this option working, because as i see the transmitting on multiple TXs is basically making each others signal hard to read. Especially for the cheap wall outlets and similar, but even confused an Arduino receiver with lpf on breadboard.
I think the source of the issue is in the nature of "lower" frequencies tend to reverb from objects and the timing must be hard on lan/wifi.

In case anything else is needed, logs or configs then please let me know.

p.s.: Apologizes if i made any mistake in the bug report, first time using github.

**Comment by CurlyMoo** [comment]
This was implemented in the rewrite code.
