### ISSUE TITLE
pilight-daemon doesn't start out of the box if webserver isn't installed

### ISSUE THREAD

**Issue by ThYpHo0n** [pilight/pilight#257]
Hey,

I'm just new to pilight but encountered a first little "flaw". If you deselect in the setup.py routine the webserver the pilight-daemon doesn't start after the setup because the /etc/pilight/config.json contains config values for the webserver which leads to an error in the daemon startup process:
[Mar 19 14:35:07:909871] pilight-daemon: ERROR: config setting "webserver-enable" is invalid

The fix was to remove the webserver relevant config values in the config.json
Ideally the setup process would be aware of the selected packages and only add the config values for the selected ones.

**Comment by CurlyMoo** [comment]
If you manually compile i also assume you are techincal enough to deal with this. Thanks for reporting though. :+1:
