### ISSUE TITLE
Race condition in rules

### ISSUE THREAD

**Issue by alcoheca** [pilight/pilight#266]
**pilight-daemon version v7.0-114-g6fa4b8b**

With my devices as:

```
		"LivingRoomWall": {
			"protocol": [ "kaku_dimmer" ],
			"id": [{
				"id": 1,
				"unit": 3
			}],
			"state": "on",
			"dimlevel": 15
		},
		"LivingRoomTable": {
			"protocol": [ "byebyestandby" ],
			"id": [{
				"id": 1,
				"unit": 11
			}],
			"state": "on"
		},
		"LivingRoomShelves": {
			"protocol": [ "kaku_dimmer" ],
			"id": [{
				"id": 1,
				"unit": 2
			}],
			"state": "on",
			"dimlevel": 15
		},
```

And a rule like

``IF LivingRoom.state IS on THEN switch DEVICE LivingRoomTable AND LivingRoomWall AND LivingRoomShelves TO on``

There is no guarantee that all three devices will switch on. I think the transmissions are being sent too close to each other and are causing interference.

Feature request would be a configurable millisecond delay between transmissions.

**Comment by pilino1234** [comment]
You can use the AFTER command for this, see the pilight wiki. 

The current way this functions is know and has been discussed on the forums already; the solution to this is to use AFTER to delay switching separate devices by about 500 milliseconds.

**Comment by CurlyMoo** [comment]
@pilino1234 already provided the solution.
