### ISSUE TITLE
Add Support for Ninja Motion/Door Sensors and Weather Stations

### ISSUE THREAD

**Issue by Toklandarr** [pilight/pilight#320]
_Please excuse me putting different things into one single Issue, I did not know how to connect it with bountysource otherwise..._

Would really like to switch to pilight from my ninja crust.

Unfortunately, I can only see (and send) my Intertechno Remote(s) and no Messages from the Ninja Weather Stations, nor the Motion/Door Sensors.

Tried both development and stable branches. Also tried Firmware v4 for the filter firmware, but that results in me not receiving anything at all... (maybe #186 is related)

https://www.bountysource.com/issues/40102477-add-support-for-ninja-motion-door-sensors-and-weather-stations

**Comment by wo-rasp** [comment]
We have 4 threads in the pilight forum for ninja devices:
- Temp Sensor
- Motion Detector
- Button
- Door Open Sensor
To determine what needs to be done, please follow the rules in the forum and provide the information required.

**Comment by Toklandarr** [comment]
Thank you for your reply wo-rasp.

I think the first step is to solve the Low-Pass-Filter Issue.
Is there a way to bypass it? I have the "official" kit from pilight.org .
Should pilight-receive be quick and reliable? I have found it to be _VERY_ hit and miss and only get output by restarting the daemon several times... 

Thank you in advance!

**Comment by wo-rasp** [comment]
We have a discussion regarding LPF on the forum:
https://forum.pilight.org/Thread-Filter-settings-in-config-json?pid=19857#pid19857

**Comment by Toklandarr** [comment]
Closing this as there is apparently no interest in debugging/fixing this and I don't have the time/RF-knowledge...

**Comment by wo-rasp** [comment]
This is not the case, as said before, we discuss it at the referenced forum.
