### ISSUE TITLE
Hardware not compatible when use kernel 4.9 for RPi2

### ISSUE THREAD

**Issue by ezar** [pilight/pilight#324]
I update kernel to the "next" branch and pilight doesn´t works anymore. 
> No compatible hardware error.

I return to 4.4 branch and works again.

**Comment by CurlyMoo** [comment]
Any idea why?

**Comment by ezar** [comment]
Seems than hardware is identified using BCM2835, not BCM2809.
Is it possible?

**Comment by CurlyMoo** [comment]
And how should this effect pilight?

**Comment by wo-rasp** [comment]
There are several changes in the Kernel, in my opinion 4.5 to 4.8 is pretty stable but 4.9 is still a bit more suited for beta testers.

More can be found on raspberry.org

**Comment by fb-pilot** [comment]
I had the same issue  - BCM2835. WiringX is cecking it. I moified raspberrypi.c and it worked.

[raspberrypi_bf.zip](https://github.com/pilight/pilight/files/737594/raspberrypi_bf.zip)

**Comment by CurlyMoo** [comment]
Can you show a diff?

**Comment by wo-rasp** [comment]
root@pi2_89:/home/pi# diff raspberrypi_bf.c /home/pi/pilight/libs/wiringx/raspberrypi.c                                      331,334d330
<       } else if(strstr(name, "BCM2835") != NULL) {
<               piModel2 = 1;
<               boardRev = 2;
<               return boardRev;
root@pi2_89:/home/pi#

**Comment by CurlyMoo** [comment]
If someone can make a PR at both pilight and wiringx.

**Comment by wo-rasp** [comment]
Submitted with link to the following forum thread/post:
https://forum.pilight.org/Thread-Boot-from-USB?pid=20427#pid20427

**Comment by wo-rasp** [comment]
Please close the PR, as PR is replaced with PR #328

**Comment by CurlyMoo** [comment]
Will close the issue as soon as the PR is merged.

**Comment by DJaeger** [comment]
Its already merged
