### ISSUE TITLE
pilight.org does not work 

### ISSUE THREAD

**Issue by chof747** [pilight/pilight#333]
Hi, I just noticed that the site pilight.org is not working any more. It's this site still active or is there another source for the documentation and the wiki? - thanks Christian

**Comment by pilino1234** [comment]
Nope, seems to be temporary maintenance. Should be back soon I guess.

**Comment by CurlyMoo** [comment]
Should be temporary. Some server issues. I mailed the hoster about it. And i also have daily backups when needed.

**Comment by chof747** [comment]
Thanks, is up and running again.
