### ISSUE TITLE
pilight doesn't send anything after rpi-update

### ISSUE THREAD

**Issue by cbajohr** [pilight/pilight#342]
I did a rpi-update today to update the firmware on my pi1. 
After rebooting, pilight does not send any signal anymore. 
Server is running normaly, server frontend also is showing up, buttons are working fine, but nothing happens after turning a device on/off.
Even the logs are not saying anything.

pilight-receive is receiving all signals normaly, also registering the sending. But nothing happens on the devices. 

Before the rpi-update, all devices worked fine.

Config is on the same state like before.

Any idea how to fix that problem?

**Comment by CurlyMoo** [comment]
This has already been covered on the forum and here on github. Also, a fix has already been made in the development code.

**Comment by cbajohr** [comment]
Is this fix covered in the nighlty builds?
