### ISSUE TITLE
Changes introduced with commit ga40f146

### ISSUE THREAD

**Issue by wo-rasp** [pilight/pilight#353]
Do to various complains of users, the changes introduced with commit ga40f146 seem to be incompatible with Kernel 4.9.x

**Comment by CurlyMoo** [comment]
It is compatible with the raspberry pi zero. I took that code from wiringPi, but maybe made some mistake. Are we 100% sure that that was the commit causing the issue?

**Comment by wo-rasp** [comment]
There was a complain on Apr-28th, but that is related to the V7 Master branch and was solved by replacing the 4.9.x kernel with a 4.4.x one.
The next complains were from May-7th and 8th and those dates are after the changes to wiringx.c were made on May-1st.

**Comment by CurlyMoo** [comment]
I got the logic from wiringPi here:
https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L938-L1014

It was implemented to distuingish the Raspberry Pi Zero from the Raspberry Pi 2, but it seems we should implement the full detection condition instead of just the logic i used.

**Comment by CurlyMoo** [comment]
Let's see how the latest commit works.

**Comment by abko** [comment]
Tested it just now (May 10) The latest nightly build works for me on my Raspberry Pi Zero running kernel 4.9.24.

**Comment by nixnuex** [comment]
Commit 136fbff fixed this problem for me. Everything works fine again! Thx!

**Comment by DJaeger** [comment]
Works now for me too
