### ISSUE TITLE
support for Xunglong OrangePi PC2 H5 

### ISSUE THREAD

**Issue by testos77** [pilight/pilight#358]
Trying to get the device working with the pilight (rewrite) branch and a 433 Mhz transmitter reciever connected to the GPIO PINS (Physical Pin 12,13). General info about the device can be found at [link](http://linux-sunxi.org/Xunlong_Orange_Pi_PC_2)
1) To compile pilight using an ARM64 based OS you'll have to add  
`/usr/lib/aarch64-linux-gnu` to CMakeLists.txt

2)Download and compile  https://github.com/kazukioishi/WiringOP H5 branch

3)` gpio readall`
`![grafik](https://user-images.githubusercontent.com/13945199/27480571-b2544744-5818-11e7-86a3-c7494b475b14.png)
4) config.json
'[...] "hardware:" {
          "433gpio:" {
             "sender:" 0,
             "receiver:" 1,
           }
}, [...]

Pilight daemon starts with error:

> error the 433gpio module is not supported on this hardware

**Comment by CurlyMoo** [comment]
You can ask for help on the pilight forum. The error you posted has been discussed tens of times before.

**Comment by testos77** [comment]
thx, I will, I did search the forum, but e.g. adding 
"gpio-platform:" "orangepipc+" to the config.json unfortunately didn't help. The GPIO settings might differ between H3 Xunglong to the H5 devices. And wiringX doesn't list the device as supported yet. If the device is already supported or won't be in the future and I'm only missing something in the configuration this issue can be closed then. .

**Comment by CurlyMoo** [comment]
If it doesn't list as supported then it isn't supported. Plain and simple :smile:
