### ISSUE TITLE
Output from bash-script to label

### ISSUE THREAD

**Issue by timherrm** [pilight/pilight#364]
Hi, 
i'm trying to write a rule like this:
`IF 1 == 1 THEN label DEVICE dimLabel TO dimmer.dimlevel`
but instead of dimmer.dimlevel i want to use the return from a bash script, or just the contents from an text file.

Is this possible?
Thanks

**Comment by CurlyMoo** [comment]
Nope, use the bash script to set a generic dimmer and use that inside a rule.

**Comment by timherrm** [comment]
thanks, solved it by calling this in the script:

`pilight-send -p generic_label -i 1 -l "12345678"  -c "#00FFFF"`
