### ISSUE TITLE
Cannot define id of bmp180 sensor

### ISSUE THREAD

**Issue by KoffeinKaio** [pilight/pilight#369]
Hey,

I wanted to add a BMP180 to pilight but it keeps crashing with:

> [Jul 31 17:15:11:886961] pilight-daemon: ERROR: config device setting #2 "id" of "bmp180sensor", invalid

config.json snippet:
```
	"devices": {
		"bmp180sensor": {
			"protocol": [ "bmp180" ],
			"id": [{
				"id":"0x77"
			}],
			"temperature": 19.1,
			"pressure": 1006.8,
			"oversampling": 1
		}
	},
```

i2cdetect:
```
root@raspberrypi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- 77
```

Pilight version: pilight-daemon version v7.0-198-g1c5c59b

**Comment by CurlyMoo** [comment]
A simple google for `bmp180 pilight forum` gives me the solution within three results.

**Comment by KoffeinKaio** [comment]
Oh well, sorry then. 
I searched the forums too but hasnt find this thread, nvm.

**Comment by CurlyMoo** [comment]
Using the development version also requires you to find your own answers. Stable is properly documented (i hope):
https://forum.pilight.org/Thread-bmp180-id-invalid
