### ISSUE TITLE
pilight-firmware repository

### ISSUE THREAD

**Issue by clarkewd** [pilight/pilight#372]
The low pass filter firmware that is included in this repository [pilight_firmware_v3.c](https://github.com/pilight/pilight/blob/master/libs/pilight/protocols/core/pilight_firmware_v3.c) has a newer commit date than the firmware in the [pilight-firmware repository](https://github.com/pilight/pilight_firmware)  - but they are both marked as v3. The code is also considerably different. What's the purpose of the other repository? If it is outdated and this repo is the newer location for the firmware, shouldn't a note be added to that repository stating so?

**Comment by CurlyMoo** [comment]
The code in the firmware repository is the actual firmware for the ATTiny. The code in the pilight repository is meant to receive a special protocol that the firmware emits to detect it's version number.
